export const TASK_CATEGORIES = [
  {
    id: 'reading',
    name: 'Reading',
    icon: '📚',
    description: 'Reading assignments, textbooks, or articles',
    color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
    focusMode: 'reading',
  },
  {
    id: 'writing',
    name: 'Writing',
    icon: '✍️',
    description: 'Essays, reports, or creative writing',
    color: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
    focusMode: 'writing',
  },
  {
    id: 'math',
    name: 'Math',
    icon: '🧮',
    description: 'Problem sets, equations, or calculations',
    color: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
    focusMode: 'deep-work',
  },
  {
    id: 'research',
    name: 'Research',
    icon: '🔍',
    description: 'Gathering and analyzing information',
    color: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
    focusMode: 'research',
  },
  {
    id: 'memorization',
    name: 'Memorization',
    icon: '🧠',
    description: 'Flashcards or rote learning',
    color: 'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300',
    focusMode: 'spaced-repetition',
  },
  {
    id: 'project',
    name: 'Project Work',
    icon: '📂',
    description: 'Group or individual projects',
    color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300',
    focusMode: 'deep-work',
  },
  {
    id: 'review',
    name: 'Review',
    icon: '📝',
    description: 'Reviewing notes or past material',
    color: 'bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-300',
    focusMode: 'active-recall',
  },
  {
    id: 'other',
    name: 'Other',
    icon: '📌',
    description: 'Any other type of task',
    color: 'bg-gray-100 text-gray-800 dark:bg-gray-800/30 dark:text-gray-300',
    focusMode: 'standard',
  },
];

export const FOCUS_MODES = {
  'standard': {
    name: 'Standard',
    description: 'Balanced focus with regular breaks',
    defaultDuration: 25,
    breakDuration: 5,
    longBreakAfter: 4,
    longBreakDuration: 15,
  },
  'deep-work': {
    name: 'Deep Work',
    description: 'Longer focus sessions for intensive work',
    defaultDuration: 50,
    breakDuration: 10,
    longBreakAfter: 3,
    longBreakDuration: 20,
  },
  'reading': {
    name: 'Reading',
    description: 'Focused reading with eye strain prevention',
    defaultDuration: 30,
    breakDuration: 10,
    longBreakAfter: 2,
    longBreakDuration: 15,
  },
  'writing': {
    name: 'Writing',
    description: 'Optimal for writing flow',
    defaultDuration: 45,
    breakDuration: 15,
    longBreakAfter: 2,
    longBreakDuration: 25,
  },
  'research': {
    name: 'Research',
    description: 'For gathering and processing information',
    defaultDuration: 40,
    breakDuration: 10,
    longBreakAfter: 3,
    longBreakDuration: 20,
  },
  'spaced-repetition': {
    name: 'Spaced Repetition',
    description: 'Short bursts for optimal memorization',
    defaultDuration: 20,
    breakDuration: 5,
    longBreakAfter: 4,
    longBreakDuration: 15,
  },
  'active-recall': {
    name: 'Active Recall',
    description: 'For testing your knowledge',
    defaultDuration: 25,
    breakDuration: 5,
    longBreakAfter: 4,
    longBreakDuration: 15,
  },
};
